### ISSUE TITLE
Failed Query

### ISSUE THREAD

**Issue by wsmorgan** [rosenbrockc/aflow#1]
```python
result = search(batch_size=50
               ).select(K.species=="Al,Co,W"
               ).select(K.stoichiometry % "0.75")
```

is evidently not a valid query because there is not JSON response:

```
ValueError: No JSON object could be decoded
```

But, instead of failing gracefully, it chokes.

**Comment by rosenbrockc** [comment]
This was a problem on the AFLUX side. It has been fixed and this query works as of Revision 0.0.5.
