### ISSUE TITLE
[Question] How to I do query for single element structures?

### ISSUE THREAD

**Issue by yanxon** [rosenbrockc/aflow#5]
Dear @rosenbrockc and @wsmorgan,

I want to search for structures that only contains Cu. I tried to use the code below. But, it returns me compound, i.e. Cu4Mg1Y1. 

```
results = search(batch_size = 100
                ).filter(K.species == 'Cu')
```

I really appreciate for your help!

**Comment by rosenbrockc** [comment]
Add an extra `.filter(K.nspecies == 1)` and it should work.

**Comment by yanxon** [comment]
It works like a charm. Thank you so much for you help!
