### ISSUE TITLE
Install aflow via conda-forge 

### ISSUE THREAD

**Issue by jan-janssen** [rosenbrockc/aflow#7]
Hi, 

I recently build the conda-forge package for aflow, you can now install it using: 

`conda install -c conda-forge aflow`

Best, 

Jan

**Comment by rosenbrockc** [comment]
Dear Jan,

thank-you for your efforts and contributions. Could you please add instructions to the main README.md and submit a pull request? Then it won't only show up in the issues. Thanks!

Best,
Conrad

**Comment by jan-janssen** [comment]
Sure I opened the corresponding pull request. In addition I can add you as an maintainer for the conda package: 
https://github.com/conda-forge/aflow-feedstock/

**Comment by jan-janssen** [comment]
There is just one more thing, can you release a new package on pip once the changes to the readme are merged? The conda package is build directly from pip and that would fix a couple of bugs with the old dependencies: 
https://github.com/conda-forge/aflow-feedstock/pull/3

**Comment by rosenbrockc** [comment]
Absolutely! I just updated the CI configuration to remove python 2 as it reaches end of life. Instead I am now testing 3.5 and 3.7 instead.  PyPI now has the latest version.
